package io.github.theredja.src2mc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtIo;
import org.junit.jupiter.api.Test;

/**
 * Reads the converter's own committed output.
 *
 * <p>This is the drift detector described in {@code docs/format.md} §6. The
 * files under {@code tests/fixtures} are generated by the Rust side and read
 * here by Minecraft's own NBT reader, so a change to what the converter writes
 * fails in this project, in the same CI run, rather than in a game log weeks
 * later.
 *
 * <p>Fixtures are uncompressed NBT. Production {@code .schem} files are gzipped;
 * the compression is not part of the contract and is left out so the golden
 * bytes depend only on what is serialized.
 */
class FormatFixtureTest {
    private static Path fixtures() {
        String dir = System.getProperty("src2mc.fixtures");
        assertNotNull(dir, "src2mc.fixtures system property is set by build.gradle");
        return Path.of(dir);
    }

    private static CompoundTag readFixture(String name) throws IOException {
        Path path = fixtures().resolve(name);
        assertTrue(
                Files.exists(path),
                "missing fixture "
                        + path
                        + " — generate it with: UPDATE_FIXTURES=1 cargo test --test fixtures");
        try (DataInputStream in =
                new DataInputStream(new BufferedInputStream(Files.newInputStream(path)))) {
            return NbtIo.read(in);
        }
    }

    /**
     * The two constants are the whole coordination mechanism, so read the Rust
     * one rather than trusting that someone updated both.
     */
    @Test
    void formatVersionMatchesTheConverter() throws IOException {
        Path lib = Path.of(System.getProperty("src2mc.repo"), "src/lib.rs");
        String source = Files.readString(lib, StandardCharsets.UTF_8);
        Matcher m =
                Pattern.compile("pub const FORMAT_VERSION: i32 = (\\d+);").matcher(source);
        assertTrue(m.find(), "no FORMAT_VERSION constant in " + lib);

        assertEquals(
                Integer.parseInt(m.group(1)),
                Src2mc.FORMAT_VERSION,
                "Src2mc.FORMAT_VERSION and src2mc::FORMAT_VERSION disagree; "
                        + "bump both in the same commit, see docs/format.md");
    }

    @Test
    void fixtureIsASpongeV3SchematicWeUnderstand() throws IOException {
        CompoundTag schematic = readFixture("tiny.nbt").getCompound("Schematic");

        assertEquals(3, schematic.getInt("Version"), "Sponge schematic version");
        assertEquals(3955, schematic.getInt("DataVersion"), "Minecraft 1.21.1");

        assertEquals(
                Src2mc.FORMAT_VERSION,
                schematic.getCompound("Metadata").getInt("src2mc:FormatVersion"),
                "docs/format.md §1 requires Metadata.src2mc:FormatVersion");
    }

    @Test
    void fixturePaletteRoundTrips() throws IOException {
        CompoundTag blocks = readFixture("tiny.nbt").getCompound("Schematic").getCompound("Blocks");
        CompoundTag palette = blocks.getCompound("Palette");

        assertTrue(palette.contains("minecraft:stone"), "palette lost minecraft:stone");
        assertTrue(palette.contains("minecraft:glass"), "palette lost minecraft:glass");
        assertTrue(blocks.getByteArray("Data").length > 0, "block data is empty");
    }
}
