org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=src2mc
mod_name=src2mc
mod_license=PolyForm Noncommercial License 1.0.0
mod_version=0.0.0-dev
mod_group_id=dev.theredja.src2mc
